uploads = []
outputs = []

[[generated]]
id = "RaV2cYGyHBDVkUgK0bbkH"
uri = "file://free-tools/lost-customers-calculator/og-image.png"
type = "image"
title = "generated_image"

[[generated]]
id = "zsAVhgoAXA6TMLhfoh5Bl"
uri = "file://free-tools/presence-score/og-image.png"
type = "image"
title = "generated_image"

[[generated]]
id = "7HyrNWYEicO8aEnpizv7O"
uri = "file://affiliates/og-image.png"
type = "image"
title = "affiliates og image dark navy gold"
