# Generated by Django 4.2.29 on 2026-05-13 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SmartQRCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.CharField(db_index=True, max_length=8, unique=True)),
                ("target_url", models.URLField(max_length=2048)),
                ("label", models.CharField(blank=True, max_length=120)),
                ("tool_source", models.CharField(max_length=64)),
                (
                    "owner_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("manage_token_hash", models.CharField(max_length=128, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "password_hash",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_ip_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="smartqr_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SmartQRScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_hash", models.CharField(max_length=64)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("user_agent_raw", models.CharField(max_length=512)),
                ("device_type", models.CharField(default="other", max_length=16)),
                ("os_family", models.CharField(default="other", max_length=32)),
                ("os_version", models.CharField(blank=True, max_length=32)),
                ("browser_family", models.CharField(default="other", max_length=32)),
                ("browser_version", models.CharField(blank=True, max_length=32)),
                ("is_bot", models.BooleanField(default=False)),
                ("referrer", models.CharField(blank=True, max_length=512)),
                ("language", models.CharField(blank=True, max_length=16)),
                ("utm_source", models.CharField(blank=True, max_length=64)),
                ("utm_medium", models.CharField(blank=True, max_length=64)),
                ("utm_campaign", models.CharField(blank=True, max_length=64)),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="smartqr.smartqrcode",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["code", "created_at"],
                        name="smartqr_sma_code_id_ad816c_idx",
                    ),
                    models.Index(
                        fields=["country"], name="smartqr_sma_country_91b884_idx"
                    ),
                    models.Index(
                        fields=["device_type"], name="smartqr_sma_device__2e0263_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="smartqrcode",
            index=models.Index(
                fields=["owner_user"], name="smartqr_sma_owner_u_3bb4b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smartqrcode",
            index=models.Index(
                fields=["tool_source"], name="smartqr_sma_tool_so_de926e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smartqrcode",
            index=models.Index(
                fields=["created_at"], name="smartqr_sma_created_a7b527_idx"
            ),
        ),
    ]
