# Generated by Django 5.2.14 on 2026-05-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostCustomerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('weekly_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lost Customer Lead',
                'verbose_name_plural': 'Lost Customer Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PresenceScoreLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('score', models.PositiveSmallIntegerField()),
                ('answers', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Presence Score Lead',
                'verbose_name_plural': 'Presence Score Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
